### ISSUE TITLE
Screening run tutorial, only one compound predicted

### ISSUE THREAD

**Issue by GattiMh** [cosconatilab/PyRMD#1]
Hello,

I have installed and run the tutorial sets both benchmarked and screening. So far so good, I have noticed that in the resulting file `database_predcitions.csv` I only have 1 molecule from MCule. What are the parameters to tweak to produce more results?

Many thanks

**Comment by gioamendola** [comment]
Hi,

The file `mcule_sample.smi` in the screening tutorial was included for illustrative purposes only. It's very small and only contains one known inhibitor. 
Screen larger databases to obtain more potentially active compounds.

For the best parameters to tweak to obtain more results, please read the "Optimizing PyRMD Performance" section in the README of the repository.

**Comment by GattiMh** [comment]
Thank you.

In the documentation, it mentions you can provide non-Chembl data as well. How does it have to be formatted? 
For the Chembl data, it seems PyRMD.py is looking for certain fields like 'Standard Value','Standard Type','Standard Relation', 'Standard Units' ecc ecc. Was wondering if they have to be called the same for the non-Chembl data files as well.

Many thanks

**Comment by gioamendola** [comment]
PyRMD should be able to read any text-based tabular data files, such as .smi SMILES files and .csv files, as long as they contain a  column of SMILES strings. If for some reason the file cannot be read by PyRMD, you could make sure that the file includes a column named "Title" and another named "Smiles". And that the file uses commas as separators

**Comment by GattiMh** [comment]
Thank you.

Does it read a column for activity as well for the non-Chembl data files or just SMILES strings?

**Comment by gioamendola** [comment]
If you tell PyRMD in the configuration file to use non-Chembl data, then it will search only for two values in the tabular file -- a column with SMILES strings and their associated name.

If you want to use activities in a non-Chembl file you'll have to manually format it like a Chembl file. Check the SI of the PyRMD manuscript to know exactly what PyRMD looks for in a Chembl file.
