### ISSUE TITLE
The number of results after screening don't match the original screening database

### ISSUE THREAD

**Issue by GattiMh** [cosconatilab/PyRMD#2]
Hello,

I have tested PyRMD on a databases to be screened that contains roughly 20 000 molecules.
I have noticed that the results I get are only 700. Is there a particular reason why I don't get all the 20 000 original molecules with their correspective predicted RMD_scores?

Many thanks

**Comment by gioamendola** [comment]
Hi,

What you described is the expected PyRMD behavior. All the molecules with an RMD score below zero (predicted non-binders) are automatically discarded from the output files. This means that all the molecules in the output are predicted to be binders, albeit with a different confidence score.

This was implemented to streamline the analysis of the results.

**Comment by GattiMh** [comment]
Thank you very much.
I've missed that molecules with an RMS below zero would automatically be discarded from the output.

Much appreciated
